name: Run on test branch only

on:
  push:
    branches:
      - test

jobs:
  echo-test-branch:
    runs-on: [self-hosted]
    steps:
      - name: Say Hello
        run: echo "âœ… You pushed to the test branch!"
